config/routes.rb
Peoplenetz::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :solutions do
    resources :solution_topics
  end
  resources :libraries do 
    resources :library_topics
  end
  resources :industries do
    resources :industry_topics
  end
  resources :cases
  resources :contacts

  match '/home', :to => 'pages#home'
  match '/specializ', :to => 'pages#specializ'
  match '/industries', :to => 'pages#industries'
  match '/solutions', :to => 'pages#solutions'
  match '/libraries', :to => 'pages#libraries'
  match '/build_case', :to => 'pages#build_case'
  match '/about', :to => 'pages#about'
  match '/why_peoplenetz', :to => 'pages#why_peoplenetz'
  match '/services', :to => 'pages#services'
  match '/sales', :to => 'pages#sales'
  match '/help', :to => 'pages#help'
  match '/careers', :to => 'pages#careers'
  match '/management', :to => 'pages#management_team'
  match '/corporate_responsibility', :to => 'pages#corporate_responsibility'
  match '/partners', :to => 'pages#partners'

  root :to => 'pages#home'

end

app/models/library.rb
# == Schema Information
#
# Table name: libraries
#
#  id          :integer(4)      not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Library < ActiveRecord::Base
  has_many :library_topics, :dependent => :destroy, :order => 'position'
  
  attr_accessible :description, :name
  
  validates :name,  :presence       => true,
                    :uniqueness     => { :case_sensitive => false }

  def to_s
    self.name
  end
  
  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @libraries }
    end
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
    @library = Library.find(params[:id])
    @library_topic = @library.library_topics.order(:position).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @library }
    end
  end

  # GET /libraries/new
  # GET /libraries/new.json
  def new
    @library = Library.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @library }
    end
  end

  # GET /libraries/1/edit
  def edit
    @library = Library.find(params[:id])
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(params[:library])

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, :notice => 'Library was successfully created.' }
        format.json { render :json => @library, :status => :created, :location => @library }
      else
        format.html { render :action => "new" }
        format.json { render :json => @library.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /libraries/1
  # PUT /libraries/1.json
  def update
    @library = Library.find(params[:id])

    respond_to do |format|
      if @library.update_attributes(params[:library])
        format.html { redirect_to @library, :notice => 'Library was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @library.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library = Library.find(params[:id])
    @library.destroy

    respond_to do |format|
      format.html { redirect_to libraries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_accordion.html.erb
	<div class="accordion" id="accordion2">
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
            Case Studies
          </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse in">
          <div class="accordion-inner">
            Coming soon
          </div>
        </div>
      </div>
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
            Brochures
          </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse">
          <div class="accordion-inner">
            Coming soon.
          </div>
        </div>
      </div>
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
            Presentations
          </a>
        </div>
        <div id="collapseThree" class="accordion-body collapse">
          <div class="accordion-inner">
            Coming soon.
          </div>
        </div>
      </div>
    </div>

app/views/libraries/_form.html.erb
<%= simple_form_for(@library) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/libraries/_topic_content.html.erb
<% if @library_topic %>
  <h4 id="topic_content_title"><%= @library_topic.title %></h4>
  <div id='topic_content'>
    <%= @library_topic.content.html_safe %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing library</h1>

<%= render 'form' %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
<h1>Listing libraries</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @libraries.each do |library| %>
  <tr>
    <td><%= library.name %></td>
    <td><%= library.description %></td>
    <td><%= link_to 'Show', library %></td>
    <td><%= link_to 'Edit', edit_library_path(library) %></td>
    <td><%= link_to 'Destroy', library, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Library', new_library_path %>

app/views/libraries/new.html.erb
<h1>New library</h1>

<%= render 'form' %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
<% content_for :title, @library %>
<%= raw display_banner('libraries', @library.name) %>

<%= render "layouts/begin_content"%>

<div class="row-fluid">
  <div class="span10">
	<div class="row-fluid">
  	  <%= @library.description.html_safe %>
	</div>
	
   <% if @library_topic %>
    <div class="row-fluid">
	  <div class="span9">
		<%= render 'topic_content' %>
	  </div>
	  <div class="span3 ">
  		<div class="well sub_topics" style="padding:5px">
		  <ul class="fonts-sitemap">
		    <% @library.library_topics.each do |topic| %>
			  <li><%= link_to topic.title, library_library_topic_path(@library, topic)+".json", :remote => true, :value => 'jdtest' %></li>
		    <% end %>	
		  </ul>
		</div>
	  </div>
	</div>
   <% end %>
  </div>

  <div class="span2">
	<%= render 'accordion'%>
  </div>
</div>

<%= render "layouts/end_content"%>