config/routes.rb
Peoplenetz::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :solutions do
    resources :solution_topics
  end
  resources :libraries do 
    resources :library_topics
  end
  resources :industries do
    resources :industry_topics
  end
  resources :cases
  resources :contacts

  match '/home', :to => 'pages#home'
  match '/specializ', :to => 'pages#specializ'
  match '/industries', :to => 'pages#industries'
  match '/solutions', :to => 'pages#solutions'
  match '/libraries', :to => 'pages#libraries'
  match '/build_case', :to => 'pages#build_case'
  match '/about', :to => 'pages#about'
  match '/why_peoplenetz', :to => 'pages#why_peoplenetz'
  match '/services', :to => 'pages#services'
  match '/sales', :to => 'pages#sales'
  match '/help', :to => 'pages#help'
  match '/careers', :to => 'pages#careers'
  match '/management', :to => 'pages#management_team'
  match '/corporate_responsibility', :to => 'pages#corporate_responsibility'
  match '/partners', :to => 'pages#partners'

  root :to => 'pages#home'

end

app/models/industry.rb
# == Schema Information
#
# Table name: industries
#
#  id             :integer(4)      not null, primary key
#  name           :string(255)
#  description    :text
#  pnetz_response :text
#  created_at     :datetime        not null
#  updated_at     :datetime        not null
#

class Industry < ActiveRecord::Base
  has_many :industry_topics, :dependent => :destroy, :order => 'position'
  
  attr_accessible :description, :name, :pnetz_response
  
  validates :name,  :presence       => true,
                    :uniqueness     => { :case_sensitive => false }
                    
  def to_s
    self.name
  end
  
  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  # GET /industries
  # GET /industries.json
  def index
    @industries = Industry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @industries }
    end
  end

  # GET /industries/1
  # GET /industries/1.json
  def show
    @industry = Industry.find(params[:id])
    @industry_topic = @industry.industry_topics.order(:position).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @industry }
    end
  end

  # GET /industries/new
  # GET /industries/new.json
  def new
    @industry = Industry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @industry }
    end
  end

  # GET /industries/1/edit
  def edit
    @industry = Industry.find(params[:id])
  end

  # POST /industries
  # POST /industries.json
  def create
    @industry = Industry.new(params[:industry])

    respond_to do |format|
      if @industry.save
        format.html { redirect_to @industry, :notice => 'Industry was successfully created.' }
        format.json { render :json => @industry, :status => :created, :location => @industry }
      else
        format.html { render :action => "new" }
        format.json { render :json => @industry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /industries/1
  # PUT /industries/1.json
  def update
    @industry = Industry.find(params[:id])

    respond_to do |format|
      if @industry.update_attributes(params[:industry])
        format.html { redirect_to @industry, :notice => 'Industry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @industry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /industries/1
  # DELETE /industries/1.json
  def destroy
    @industry = Industry.find(params[:id])
    @industry.destroy

    respond_to do |format|
      format.html { redirect_to industries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/views/industries/_form.html.erb
<%= simple_form_for(@industry) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :pnetz_response %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/industries/_topic_content.html.erb
<% if @industry_topic %>
  <h4 id="topic_content_title"><%= @industry_topic.title %></h4>
  <div id='topic_content'>
    <%= @industry_topic.content.html_safe %>
  </div>
<% end %>

app/views/industries/edit.html.erb
<h1>Editing industry</h1>

<%= render 'form' %>

<%= link_to 'Show', @industry %> |
<%= link_to 'Back', industries_path %>

app/views/industries/index.html.erb
<h1>Listing industries</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Pnetz solution</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @industries.each do |industry| %>
  <tr>
    <td><%= industry.name %></td>
    <td><%= industry.description %></td>
    <td><%= industry.pnetz_response %></td>
    <td><%= link_to 'Show', industry %></td>
    <td><%= link_to 'Edit', edit_industry_path(industry) %></td>
    <td><%= link_to 'Destroy', industry, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Industry', new_industry_path %>

app/views/industries/new.html.erb
<h1>New industry</h1>

<%= render 'form' %>

<%= link_to 'Back', industries_path %>

app/views/industries/show.html.erb
<% content_for :title, @industry %>
<%= raw display_banner('industries', @industry.name) %>

<%= render "layouts/begin_content"%>

<div class="row-fluid">
  <div class="span10">
	<div class="row-fluid">
  	  <%= @industry.description.html_safe %>
	</div>
	
   <% if @industry_topic %>
    <div class="row-fluid">
	  <div class="span9">
		<%= render 'topic_content' %>
	  </div>
	  <div class="span3 ">
  		<div class="well sub_topics" style="padding:5px">
		  <ul class="fonts-sitemap">
		    <% @industry.industry_topics.each do |topic| %>
			  <li><%= link_to topic.title, industry_industry_topic_path(@industry, topic)+".json", :remote => true, :value => 'jdtest' %></li>
		    <% end %>	
		  </ul>
		</div>
	  </div>
	</div>
   <% end %>
  </div>

  <div class="span2">
	<%= render 'libraries/accordion'%>
  </div>
</div>

<%= render "layouts/end_content"%>