config/routes.rb
Peoplenetz::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :solutions do
    resources :solution_topics
  end
  resources :libraries do 
    resources :library_topics
  end
  resources :industries do
    resources :industry_topics
  end
  resources :cases
  resources :contacts

  match '/home', :to => 'pages#home'
  match '/specializ', :to => 'pages#specializ'
  match '/industries', :to => 'pages#industries'
  match '/solutions', :to => 'pages#solutions'
  match '/libraries', :to => 'pages#libraries'
  match '/build_case', :to => 'pages#build_case'
  match '/about', :to => 'pages#about'
  match '/why_peoplenetz', :to => 'pages#why_peoplenetz'
  match '/services', :to => 'pages#services'
  match '/sales', :to => 'pages#sales'
  match '/help', :to => 'pages#help'
  match '/careers', :to => 'pages#careers'
  match '/management', :to => 'pages#management_team'
  match '/corporate_responsibility', :to => 'pages#corporate_responsibility'
  match '/partners', :to => 'pages#partners'

  root :to => 'pages#home'

end

app/models/solution.rb
# == Schema Information
#
# Table name: solutions
#
#  id             :integer(4)      not null, primary key
#  name           :string(255)
#  description    :text
#  pnetz_solution :text
#  created_at     :datetime        not null
#  updated_at     :datetime        not null
#

class Solution < ActiveRecord::Base
  has_many :solution_topics, :dependent => :destroy, :order => 'position'
  
  attr_accessible :description, :name, :pnetz_solution

  validates :name,  :presence       => true,
                    :uniqueness     => { :case_sensitive => false }
                    
  def to_s
    self.name
  end
  
  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  # GET /solutions
  # GET /solutions.json
  def index
    @solutions = Solution.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @solutions }
    end
  end

  # GET /solutions/1
  # GET /solutions/1.json
  def show
    @solution = Solution.find(params[:id])
    @solution_topic = @solution.solution_topics.order(:position).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @solution }
    end
  end

  # GET /solutions/new
  # GET /solutions/new.json
  def new
    @solution = Solution.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @solution }
    end
  end

  # GET /solutions/1/edit
  def edit
    @solution = Solution.find(params[:id])
  end

  # POST /solutions
  # POST /solutions.json
  def create
    @solution = Solution.new(params[:solution])

    respond_to do |format|
      if @solution.save
        format.html { redirect_to @solution, :notice => 'Solution was successfully created.' }
        format.json { render :json => @solution, :status => :created, :location => @solution }
      else
        format.html { render :action => "new" }
        format.json { render :json => @solution.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /solutions/1
  # PUT /solutions/1.json
  def update
    @solution = Solution.find(params[:id])

    respond_to do |format|
      if @solution.update_attributes(params[:solution])
        format.html { redirect_to @solution, :notice => 'Solution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @solution.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /solutions/1
  # DELETE /solutions/1.json
  def destroy
    @solution = Solution.find(params[:id])
    @solution.destroy

    respond_to do |format|
      format.html { redirect_to solutions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/solutions/_form.html.erb
<%= simple_form_for(@solution) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :pnetz_solution %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/solutions/_topic_content.html.erb
<% if @solution_topic %>
  <h4 id="topic_content_title"><%= @solution_topic.title %></h4>
  <div id='topic_content'>
    <%= @solution_topic.content.html_safe %>
  </div>
<% end %>

app/views/solutions/edit.html.erb
<h1>Editing solution</h1>

<%= render 'form' %>

<%= link_to 'Show', @solution %> |
<%= link_to 'Back', solutions_path %>

app/views/solutions/index.html.erb
<h1>Listing solutions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Pnetz solution</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @solutions.each do |solution| %>
  <tr>
    <td><%= solution.name %></td>
    <td><%= solution.description %></td>
    <td><%= solution.pnetz_solution %></td>
    <td><%= link_to 'Show', solution %></td>
    <td><%= link_to 'Edit', edit_solution_path(solution) %></td>
    <td><%= link_to 'Destroy', solution, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Solution', new_solution_path %>

app/views/solutions/new.html.erb
<h1>New solution</h1>

<%= render 'form' %>

<%= link_to 'Back', solutions_path %>

app/views/solutions/show.html.erb
<% content_for :title, @solution%>
<%= raw display_banner('solutions', @solution.name) %>

<%= render "layouts/begin_content"%>

<div class="row-fluid">
  <div class="span10">
	<div class="row-fluid">
  	  <%= @solution.description.html_safe %>
	</div>
	
   <% if @solution_topic %>
    <div class="row-fluid">
	  <div class="span9">
		<%= render 'topic_content' %>
	  </div>
	  <div class="span3 ">
  		<div class="well sub_topics" style="padding:5px">
		  <ul class="fonts-sitemap">
		    <% @solution.solution_topics.each do |topic| %>
			  <li><%= link_to topic.title, solution_solution_topic_path(@solution, topic)+".json", :remote => true, :value => 'jdtest' %></li>
		    <% end %>	
		  </ul>
		</div>
	  </div>
	</div>
   <% end %>
  </div>

  <div class="span2">
	<%= render 'libraries/accordion'%>
  </div>
</div>

<%= render "layouts/end_content" %>