config/routes.rb
Peoplenetz::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :solutions do
    resources :solution_topics
  end
  resources :libraries do 
    resources :library_topics
  end
  resources :industries do
    resources :industry_topics
  end
  resources :cases
  resources :contacts

  match '/home', :to => 'pages#home'
  match '/specializ', :to => 'pages#specializ'
  match '/industries', :to => 'pages#industries'
  match '/solutions', :to => 'pages#solutions'
  match '/libraries', :to => 'pages#libraries'
  match '/build_case', :to => 'pages#build_case'
  match '/about', :to => 'pages#about'
  match '/why_peoplenetz', :to => 'pages#why_peoplenetz'
  match '/services', :to => 'pages#services'
  match '/sales', :to => 'pages#sales'
  match '/help', :to => 'pages#help'
  match '/careers', :to => 'pages#careers'
  match '/management', :to => 'pages#management_team'
  match '/corporate_responsibility', :to => 'pages#corporate_responsibility'
  match '/partners', :to => 'pages#partners'

  root :to => 'pages#home'

end

app/views/layouts/_begin_content.html.erb
<div class="container">
    <div class="content">

app/views/layouts/_end_content.html.erb
      <div class="push"></div>
    </div><!-- /content -->
</div><!-- /container -->

app/views/layouts/_footer.html.erb
<footer>
	<div class="container" >
	  <div class="content">
		<div class="row">
	  	  <div class="span3 ">
				<h1 class="fonts-sitemap-title">Presentations</h1>
				<ul class="fonts-sitemap">
				  	<li><a href="../assets/documents/presentations/RS_Specializ_Presentation.pptx">Accelerating Risk Management</a></li>
					<li><a href="../assets/documents/presentations/PM_Specializ_Presentation.pptx">Accelerating Project Management</a></li>
					<li><a href="../assets/documents/presentations/OHS_Specializ_Presentation.pptx">Automating OH&S Health Assessments</a></li>
				</ul>
		  </div>
	
		  <div class="span2">
				<h1 class="fonts-sitemap-title">Ways to Buy</h1>
				<ul class="fonts-sitemap">
					<li><%= link_to 'Hosted Enterprise', sales_path %></li>
					<li><%= link_to 'Hosted Project', sales_path %></li>
					<li><%= link_to 'On Premises Enterprise', sales_path %></li>
					<li><%= link_to 'On Premises Project', sales_path %></li>
				</ul>
		  </div>
	
		  <div class="span2">
				<h1 class="fonts-sitemap-title">Help</h1>
				<ul class="fonts-sitemap">
					<li><%= link_to 'Web Training', help_path %></li>
					<li><%= link_to 'On-site Training', help_path %></li>
					<li><%= link_to 'Classroom Training', help_path %></li>
					<li><%= link_to 'User Manuals', help_path %></li>
				</ul>
		  </div>
		  <div class="span3">
				<h1 class="fonts-sitemap-title">Success Stories</h1>
				<ul class="fonts-sitemap">
					<li>Process Improvement of the AP Function</li>
					<li>Risk Management of Shared Services</li>
					<li>Compliance Management Using Controls Self-Assessment</li>
					<li>SAP Business Requirements</li>
					<li>Business Rule Creation for Financial Transformation</li>
				</ul>
		  </div>
	
		  <div class="span2">
				<h1 class="fonts-sitemap-title">Company</h1>
				<ul class="fonts-sitemap">
					<li><%= link_to 'About Us', about_path %></li>
					<li><%= link_to 'Contact Us', new_contact_path %></li>
					<li><%= link_to 'Management Team', management_path %></li>
					<li><%= link_to 'Partners', partners_path %></li>
					<li><%= link_to 'Careers', careers_path %></li>
					<li><%= link_to 'Corporate Responsibility', corporate_responsibility_path %></li>
				</ul>
	 	  </div>
	    </div>	

		<div class="row">
	  	  <div class="span2">
  			<p>&copy; Peoplenetz, 2012</p>
		  </div>
		</div>

	  </div> <!--/content -->
	</div> <!--/container -->

</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">

  <div id="social">
    <%= link_to image_tag('icons/facebook.png'), "http://www.facebook.com/Peoplenetz", :target => "_blank" %>
    <%= link_to image_tag('icons/twitter.png'), "https://twitter.com/#!/Peoplenetz", :target => "_blank" %>
    <%= link_to image_tag('icons/linkedin.png'), "http://www.linkedin.com/company/1871259", :target => "_blank" %>
  </div>

  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="<%= root_path %>"> <%= image_tag('peoplenetz.png', :size => "98x25") %></a>
      <div class="container nav-collapse">
      	<ul class="nav">
              <li><%= link_to "Why Peoplenetz", why_peoplenetz_path  %></li>
              
			  <li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Industries<b class="caret"></b></a>
 				<ul class="dropdown-menu">
				  <% Industry.all(:order => "name").each do |industry| %>
					<li><%= link_to industry.name, industry %></li>
				  <% end %>
				</ul>
			  </li>

              <li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Solutions<b class="caret"></b></a>
 				<ul class="dropdown-menu">
				  <% Solution.all(:order => "name").each do |solution| %>
					<li><%= link_to solution.name, solution %></li>
				  <% end %>
				</ul>
			  </li>
			  
		      <li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Libraries<b class="caret"></b></a>
 				<ul class="dropdown-menu">
				  <% Library.all(:order => "name").each do |library| %>
					<li><%= link_to library.name, library %></li>
				  <% end %>
				</ul>
			  </li>
              <li><%= link_to "Build Your Business Case", new_case_path  %></li>
              <li><%= link_to "Services", services_path  %></li>
 			  <li><%= link_to "Request a Demo", new_contact_path  %></li>
      	</ul>
        
      </div><!--/.nav-collapse -->
        
    </div>
  </div>
</div>

app/views/layouts/_site_map.html.erb
	<div id="container">
	  <div id="content">
		<div class="row">
	  	  <div class="span2 offset1">
				<ul class="fonts-sitemap">
				  	<li>Accelerating Risk Management</li>
					<li>Accelerating Project Management</li>
					<li>Automating OH&S Health Assessments</li>
				</ul>
		  </div>
	
		  <div class="span2">
				<ul class="fonts-sitemap">
					<li><%= link_to 'Hosted Enterprise', sales_path %></li>
					<li><%= link_to 'Hosted Project', sales_path %></li>
					<li><%= link_to 'On Premises Enterprise', sales_path %></li>
					<li><%= link_to 'On Premises Project', sales_path %></li>
				</ul>
		  </div>
	
		  <div class="span2">
				<ul class="fonts-sitemap">
					<li><%= link_to 'Web Training', help_path %></li>
					<li><%= link_to 'On-site Training', help_path %></li>
					<li><%= link_to 'Classroom Training', help_path %></li>
					<li><%= link_to 'User Manuals', help_path %></li>
				</ul>
		  </div>
		  <div class="span3">
				<ul class="fonts-sitemap">
					<li>Process Improvement of the AP Function</li>
					<li>Risk Management of Shared Services</li>
					<li>Compliance Management Using Controls Self-Assessment</li>
					<li>SAP Business Requirements</li>
					<li>Business Rule Creation for Financial Transformation</li>
				</ul>
		  </div>
	
		  <div class="span2">
				<ul class="fonts-sitemap">
					<li><%= link_to 'About Us', about_path %></li>
					<li><%= link_to 'Contact Us', new_contact_path %></li>
					<li><%= link_to 'Management Team', management_path %></li>
					<li><%= link_to 'Partners', partners_path %></li>
					<li><%= link_to 'Careers', careers_path %></li>
					<li><%= link_to 'Corporate Responsibility', corporate_responsibility_path %></li>
				</ul>
	 	  </div>
	
	
	    </div>	
	  </div> <!--/content -->
	</div> <!--/container -->



  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? ("Peoplenetz | " + yield(:title)) : "Peoplenetz" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

	<%= stylesheet_link_tag "peoplenetz", :media => "all" %>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut-icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>
	<div class="wrapper">
      <%= render 'layouts/header' %>
	  <%= yield %>
	  
	</div> <!-- /wrapper -->

	<%= render 'layouts/footer'%>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>